# Generated by Django 6.0.4 on 2026-04-30 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='The uploaded PDF file.', upload_to='pdfs/%Y/%m/%d/')),
                ('original_filename', models.CharField(help_text='Original filename as uploaded by the user.', max_length=255)),
                ('num_pages', models.IntegerField(default=0, help_text='Number of pages extracted from the PDF.')),
                ('num_chunks', models.IntegerField(default=0, help_text='Number of text chunks after splitting.')),
                ('is_processed', models.BooleanField(default=False, help_text='Whether embeddings have been generated and stored.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='The user who uploaded this PDF.', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_pdfs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uploaded PDF',
                'verbose_name_plural': 'Uploaded PDFs',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
